#!/usr/bin/env bash
set -Eeuo pipefail

# Gate 28: the shipped JSON Schema's `widget.type` enum stays in sync with
# the widget catalogue (the single source of truth).
# Spec: docs/cookbook/14-gates-catalogue.md §28
# Pass: `node scripts/gen-schema-enum.mjs --check` reports the schema is in
#       sync — every catalogued widget type is in the enum and vice versa,
#       and the file is prettier-formatted.
# Fail: the enum drifted from the catalogue (a widget was added/removed
#       without regenerating the schema).
# Skip: node is unavailable, or esbuild/prettier are not installed
#       (lean runtime install); CI installs devDeps so it runs there.
#
# Mode: STRICT. The enum is generated by the `prebuild` step; this gate keeps
# the checked-in copy honest so a stale schema can't ship.

# shellcheck source=lib/common.sh
. "$(dirname "$0")/lib/common.sh"

if ! have_cmd node; then
  skip_gate "node not available on PATH"
fi

gen_script="$(repo_path scripts/gen-schema-enum.mjs)"
if [ ! -f "${gen_script}" ]; then
  skip_gate "scripts/gen-schema-enum.mjs not present"
fi

esbuild_pkg="$(repo_path node_modules/esbuild/package.json)"
prettier_pkg="$(repo_path node_modules/prettier/package.json)"
if [ ! -f "${esbuild_pkg}" ] || [ ! -f "${prettier_pkg}" ]; then
  skip_gate "esbuild/prettier not installed; run \`pnpm install\` to activate"
fi

if node "${gen_script}" --check; then
  pass_gate "widget.type enum is in sync with the catalogue"
else
  fail_gate "widget.type enum is stale — run \`node scripts/gen-schema-enum.mjs\`"
fi
